### ISSUE TITLE
create a better system for channel/column attributes

### ISSUE THREAD

**Issue by kylerbrown** [kylerbrown/bark#12]
### SampledData:
+ attribute called `columns` whose value will be a dictionary of the same length as the number of channels, with integer keys that correspond to each channel's column in the data matrix. The value each dictionary will be a dictionary of attributes unique to the corresponding channel in the SampleData file.
+ required channel attributes: `units`, `unit_scale` is defined but optional.

Example:
```yaml
- columns:
  0:
    units: uV
    name: hvc_1
    unit_scale: 0.196
  1: 
    units: V
    name: mic
    unit_scale: 0.3
```

### EventData:
+ EventData follows the same rules, but keys of the dictionary must instead match the column names specified in the first line of the CSV.

Example:
```yaml
- columns:
  start:
    units: s
  stop: 
    units: s
  name:
    units: null
  score:
    units: null
```

Some implementation issues:  We may want to represent these in python as OrderedDicts, and we'll need to write some checks that the names are unique. For SampledData, keys must also start at 0 and be contiguous.

@gfetterman  thoughts?
